### ISSUE TITLE
Trojan.Gen.9?

### ISSUE THREAD

**Issue by BeastTheWoggo** [BigAtomikku/VRC-Spotify-OSC#3]
![Screenshot (133)](https://github.com/BigAtomikku/VRC-Spotify-OSC/assets/74581162/44c682fe-6bd9-412d-80a0-83584909c334)

Hmmm :/

**Comment by BigAtomikku** [comment]
That's odd. I don't know much about virus detection software and why it would flag that. I do know that Norton and McAfee are seen as pretty bad though. I'll look into it though

**Comment by BeastTheWoggo** [comment]
Windows defender also flags it. I get if its an issue with pyinstaller. Can't be too careful with technology now a days.

**Comment by BigAtomikku** [comment]
Fix coming in 2.0.1. Had to disable one-file mode

**Comment by BigAtomikku** [comment]
See 2.0.1 for potential fix
